from dotenv import load_dotenv
load_dotenv()
import os
from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from forecast_models import ForecastRequest, compute_baseline

llm = ChatOpenAI(
    model="groq/compound",
    temperature=0.3,
    api_key="omni",
    base_url="http://localhost:20128/v1"
).with_retry(stop_after_attempt=4)

MOCK_MODE = False  # <--- SET TO False AND UPDATE MODEL STRING WHEN READY FOR LIVE

async def call_llm(prompt: str, node_type: str) -> str:
    if MOCK_MODE:
        if node_type == "analyst":
            return "Your current Vercel serverless infrastructure will hit severe cold-start latency walls and connection limits at this scale. Stateless functions cannot maintain persistent GPU inference queues, leading to unpredictable compute costs and dropped requests during traffic spikes."
        elif node_type == "architect":
            return "We recommend migrating to a dedicated FastAPI async gateway fronting a vLLM cluster on AWS EC2. This enables continuous request batching, persistent KV cache, and utilization-based autoscaling, dropping your cost-per-token by roughly 40% while guaranteeing sub-200ms latency."
        return ""
    
    # Live LLM call
    res = await llm.ainvoke([HumanMessage(content=prompt)])
    return res.content

class ForecastState(TypedDict):
    request: ForecastRequest
    baseline: dict
    cost_analysis: str
    recommendation: str
    report_markdown: str

ASCII_RULE = "Use plain ASCII only. No emojis, no special symbols."

async def baseline_node(state: ForecastState) -> dict:
    return {"baseline": compute_baseline(state["request"])}

async def analyst_node(state: ForecastState) -> dict:
    req, base = state["request"], state["baseline"]
    prompt = f"""You are a Senior AI Infrastructure Engineer at Neural Forge Hub.
A founder submitted these planning metrics for their AI product:
- Expected MAU: {req.expected_mau}
- AI requests per user/month: {req.requests_per_user_month}
- Tokens per request: {req.tokens_per_request}
- Model tier: {req.model_tier}
- Current infrastructure: {req.current_infrastructure}

Our deterministic baseline calculator produced:
- Monthly requests: {base['monthly_requests']}
- Total tokens/month: {base['total_tokens_month']}
- Estimated GPU: {base['gpu_type']}, ~{base['est_gpu_hours_month']} GPU-hours/month
- Estimated monthly cost band: ${base['est_monthly_cost_low_usd']} - ${base['est_monthly_cost_high_usd']}

Write a blunt 3-4 sentence analysis of where their CURRENT infrastructure ({req.current_infrastructure}) will fail at this load (cold starts, WebSocket limits, GPU quota walls, cost cliffs). {ASCII_RULE}"""
    return {"cost_analysis": await call_llm(prompt, "analyst")}

async def architect_node(state: ForecastState) -> dict:
    req, base = state["request"], state["baseline"]
    prompt = f"""Based on this analysis: {state['cost_analysis']}
Recommend a concrete Neural Forge Hub target architecture for a {req.model_tier} workload at {base['total_tokens_month']} tokens/month.
Name specific components (vLLM vs TensorRT-LLM vs managed endpoints, FastAPI async gateway, caching layer, autoscaling policy). 3-4 sentences, decisive, no hedging. {ASCII_RULE}"""
    return {"recommendation": await call_llm(prompt, "architect")}

async def compiler_node(state: ForecastState) -> dict:
    req, base = state["request"], state["baseline"]
    md = f"""# AI Infrastructure Blueprint: {req.company_name}

## 1. Deterministic Baseline (Planning Estimates)
- Monthly requests: {base['monthly_requests']:,}
- Total tokens/month: {base['total_tokens_month']:,}
- Compute profile: {base['gpu_type']} / ~{base['est_gpu_hours_month']} GPU-hours
- Estimated monthly cost band: ${base['est_monthly_cost_low_usd']:,} - ${base['est_monthly_cost_high_usd']:,}

## 2. Failure Analysis
{state['cost_analysis']}

## 3. NFH Target Architecture
{state['recommendation']}

---
Estimates are planning figures, not benchmarks. Generated by the Neural Forge Hub Engineering Swarm.
Ready to build this? Book an architecture review at cal.com/neural-forge-hub"""
    return {"report_markdown": md}

workflow = StateGraph(ForecastState)
workflow.add_node("baseline", baseline_node)
workflow.add_node("analyst", analyst_node)
workflow.add_node("architect", architect_node)
workflow.add_node("compiler", compiler_node)
workflow.set_entry_point("baseline")
workflow.add_edge("baseline", "analyst")
workflow.add_edge("analyst", "architect")
workflow.add_edge("architect", "compiler")
workflow.add_edge("compiler", END)
forecast_graph = workflow.compile()

async def run_forecast(req: ForecastRequest) -> dict:
    state = await forecast_graph.ainvoke({
        "request": req, "baseline": {}, "cost_analysis": "",
        "recommendation": "", "report_markdown": ""
    })
    return state
